manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: petejohanson
      revision: test-bt-instant-passed-fix
      import: app/west.yml
  self:
    path: config
